// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: level.proto

package level

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LevelData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Store ALL nodes here in a flat list
	Nodes []*BSPNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// Index of the root node in the list above (-1 for empty tree)
	RootIndex int32 `protobuf:"varint,2,opt,name=root_index,json=rootIndex,proto3" json:"root_index,omitempty"`
	// Ground tiles for visual rendering
	Ground        []*Tile `protobuf:"bytes,3,rep,name=ground,proto3" json:"ground,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelData) Reset() {
	*x = LevelData{}
	mi := &file_level_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelData) ProtoMessage() {}

func (x *LevelData) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelData.ProtoReflect.Descriptor instead.
func (*LevelData) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{0}
}

func (x *LevelData) GetNodes() []*BSPNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *LevelData) GetRootIndex() int32 {
	if x != nil {
		return x.RootIndex
	}
	return 0
}

func (x *LevelData) GetGround() []*Tile {
	if x != nil {
		return x.Ground
	}
	return nil
}

type BSPNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A node is strictly one of these two things.
	//
	// Types that are valid to be assigned to Type:
	//
	//	*BSPNode_Split
	//	*BSPNode_Leaf
	Type          isBSPNode_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BSPNode) Reset() {
	*x = BSPNode{}
	mi := &file_level_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BSPNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPNode) ProtoMessage() {}

func (x *BSPNode) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPNode.ProtoReflect.Descriptor instead.
func (*BSPNode) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{1}
}

func (x *BSPNode) GetType() isBSPNode_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *BSPNode) GetSplit() *Split {
	if x != nil {
		if x, ok := x.Type.(*BSPNode_Split); ok {
			return x.Split
		}
	}
	return nil
}

func (x *BSPNode) GetLeaf() *Leaf {
	if x != nil {
		if x, ok := x.Type.(*BSPNode_Leaf); ok {
			return x.Leaf
		}
	}
	return nil
}

type isBSPNode_Type interface {
	isBSPNode_Type()
}

type BSPNode_Split struct {
	Split *Split `protobuf:"bytes,1,opt,name=split,proto3,oneof"`
}

type BSPNode_Leaf struct {
	Leaf *Leaf `protobuf:"bytes,2,opt,name=leaf,proto3,oneof"`
}

func (*BSPNode_Split) isBSPNode_Type() {}

func (*BSPNode_Leaf) isBSPNode_Type() {}

type Split struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Plane (Line in 2D): Normal * Point = Distance
	NormalX  float32 `protobuf:"fixed32,1,opt,name=normal_x,json=normalX,proto3" json:"normal_x,omitempty"`
	NormalY  float32 `protobuf:"fixed32,2,opt,name=normal_y,json=normalY,proto3" json:"normal_y,omitempty"`
	Distance float32 `protobuf:"fixed32,3,opt,name=distance,proto3" json:"distance,omitempty"`
	// Instead of nesting, point to the index in the 'nodes' array
	FrontIndex    int32 `protobuf:"varint,4,opt,name=front_index,json=frontIndex,proto3" json:"front_index,omitempty"`
	BackIndex     int32 `protobuf:"varint,5,opt,name=back_index,json=backIndex,proto3" json:"back_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Split) Reset() {
	*x = Split{}
	mi := &file_level_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Split) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Split) ProtoMessage() {}

func (x *Split) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Split.ProtoReflect.Descriptor instead.
func (*Split) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{2}
}

func (x *Split) GetNormalX() float32 {
	if x != nil {
		return x.NormalX
	}
	return 0
}

func (x *Split) GetNormalY() float32 {
	if x != nil {
		return x.NormalY
	}
	return 0
}

func (x *Split) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Split) GetFrontIndex() int32 {
	if x != nil {
		return x.FrontIndex
	}
	return 0
}

func (x *Split) GetBackIndex() int32 {
	if x != nil {
		return x.BackIndex
	}
	return 0
}

type Leaf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actual content index (e.g., sector ID, polygons)
	SectorId       int32   `protobuf:"varint,1,opt,name=sector_id,json=sectorId,proto3" json:"sector_id,omitempty"`
	PolygonIndices []int32 `protobuf:"varint,2,rep,packed,name=polygon_indices,json=polygonIndices,proto3" json:"polygon_indices,omitempty"`
	IsSolid        bool    `protobuf:"varint,3,opt,name=is_solid,json=isSolid,proto3" json:"is_solid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Leaf) Reset() {
	*x = Leaf{}
	mi := &file_level_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leaf) ProtoMessage() {}

func (x *Leaf) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leaf.ProtoReflect.Descriptor instead.
func (*Leaf) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{3}
}

func (x *Leaf) GetSectorId() int32 {
	if x != nil {
		return x.SectorId
	}
	return 0
}

func (x *Leaf) GetPolygonIndices() []int32 {
	if x != nil {
		return x.PolygonIndices
	}
	return nil
}

func (x *Leaf) GetIsSolid() bool {
	if x != nil {
		return x.IsSolid
	}
	return false
}

type Vec2I struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2I) Reset() {
	*x = Vec2I{}
	mi := &file_level_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2I) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2I) ProtoMessage() {}

func (x *Vec2I) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2I.ProtoReflect.Descriptor instead.
func (*Vec2I) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{4}
}

func (x *Vec2I) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2I) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Tile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Vec2I                 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Texture       string                 `protobuf:"bytes,2,opt,name=texture,proto3" json:"texture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tile) Reset() {
	*x = Tile{}
	mi := &file_level_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{5}
}

func (x *Tile) GetPosition() *Vec2I {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Tile) GetTexture() string {
	if x != nil {
		return x.Texture
	}
	return ""
}

var File_level_proto protoreflect.FileDescriptor

const file_level_proto_rawDesc = "" +
	"\n" +
	"\vlevel.proto\x12\aventure\"y\n" +
	"\tLevelData\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.venture.BSPNodeR\x05nodes\x12\x1d\n" +
	"\n" +
	"root_index\x18\x02 \x01(\x05R\trootIndex\x12%\n" +
	"\x06ground\x18\x03 \x03(\v2\r.venture.TileR\x06ground\"^\n" +
	"\aBSPNode\x12&\n" +
	"\x05split\x18\x01 \x01(\v2\x0e.venture.SplitH\x00R\x05split\x12#\n" +
	"\x04leaf\x18\x02 \x01(\v2\r.venture.LeafH\x00R\x04leafB\x06\n" +
	"\x04type\"\x99\x01\n" +
	"\x05Split\x12\x19\n" +
	"\bnormal_x\x18\x01 \x01(\x02R\anormalX\x12\x19\n" +
	"\bnormal_y\x18\x02 \x01(\x02R\anormalY\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x02R\bdistance\x12\x1f\n" +
	"\vfront_index\x18\x04 \x01(\x05R\n" +
	"frontIndex\x12\x1d\n" +
	"\n" +
	"back_index\x18\x05 \x01(\x05R\tbackIndex\"g\n" +
	"\x04Leaf\x12\x1b\n" +
	"\tsector_id\x18\x01 \x01(\x05R\bsectorId\x12'\n" +
	"\x0fpolygon_indices\x18\x02 \x03(\x05R\x0epolygonIndices\x12\x19\n" +
	"\bis_solid\x18\x03 \x01(\bR\aisSolid\"#\n" +
	"\x05Vec2i\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"L\n" +
	"\x04Tile\x12*\n" +
	"\bposition\x18\x01 \x01(\v2\x0e.venture.Vec2iR\bposition\x12\x18\n" +
	"\atexture\x18\x02 \x01(\tR\atextureB2Z0github.com/bloodmagesoftware/venture/proto/levelb\x06proto3"

var (
	file_level_proto_rawDescOnce sync.Once
	file_level_proto_rawDescData []byte
)

func file_level_proto_rawDescGZIP() []byte {
	file_level_proto_rawDescOnce.Do(func() {
		file_level_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_level_proto_rawDesc), len(file_level_proto_rawDesc)))
	})
	return file_level_proto_rawDescData
}

var file_level_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_level_proto_goTypes = []any{
	(*LevelData)(nil), // 0: venture.LevelData
	(*BSPNode)(nil),   // 1: venture.BSPNode
	(*Split)(nil),     // 2: venture.Split
	(*Leaf)(nil),      // 3: venture.Leaf
	(*Vec2I)(nil),     // 4: venture.Vec2i
	(*Tile)(nil),      // 5: venture.Tile
}
var file_level_proto_depIdxs = []int32{
	1, // 0: venture.LevelData.nodes:type_name -> venture.BSPNode
	5, // 1: venture.LevelData.ground:type_name -> venture.Tile
	2, // 2: venture.BSPNode.split:type_name -> venture.Split
	3, // 3: venture.BSPNode.leaf:type_name -> venture.Leaf
	4, // 4: venture.Tile.position:type_name -> venture.Vec2i
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_level_proto_init() }
func file_level_proto_init() {
	if File_level_proto != nil {
		return
	}
	file_level_proto_msgTypes[1].OneofWrappers = []any{
		(*BSPNode_Split)(nil),
		(*BSPNode_Leaf)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_level_proto_rawDesc), len(file_level_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_level_proto_goTypes,
		DependencyIndexes: file_level_proto_depIdxs,
		MessageInfos:      file_level_proto_msgTypes,
	}.Build()
	File_level_proto = out.File
	file_level_proto_goTypes = nil
	file_level_proto_depIdxs = nil
}
